kenz-gelsoft/wxRust2

doxybindgen.toml
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs

Block wxGTK unsupported APIs for wx3.1 temporarily

---

.github/workflows/rust.yml
codegen2.py
doxybindgen.toml
doxybindgen/binding.py
doxybindgen/model.py
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs

closes https://github.com/kenz-gelsoft/wxRust2/issues/42

Generate platform specific APIs as conditional compilation

---

.github/workflows/rust.yml

Add following tasks in GitHub Actions:
* Cache cargo build result to speed up
* Check code formatted

Some GitHub Actions improvement

---

doxybindgen/binding.py
wx-base/src/generated.rs
wx-core/src/generated.rs

fixes https://github.com/kenz-gelsoft/wxRust2/issues/57

Type name based generic parameter names

---

samples/hello/src/main.rs
samples/minimal/src/main.rs
samples/wrapsizer/src/main.rs
wx-core/src/lib.rs

closes https://github.com/kenz-gelsoft/wxRust2/issues/63

Simple builders

---

doxybindgen.toml
doxybindgen/binding.py
doxybindgen/model.py
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

- Support param named `box` keyword
- wxStaticBox binding
- Make Notebook builder

Widgets sample without page

---

doxybindgen/model.py
samples/widgets/src/button.rs
samples/widgets/src/checkbox.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs

- Implement CheckBox page of widgets sample
- Implement switching tabs of widgets sample
- with following fix and extension of wxRust
- wxCheckBoxState type

Widgets checkbox

---

codegen2.py
doxybindgen.toml
samples/widgets/src/choice.rs
samples/widgets/src/clrpicker.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented ColourPicker page with:
- Generate wxColourPickerCtrl binding
- Add Builder for wx::ColourPickerCtrl

Widgets sample: ColourPicker page

---

doxybindgen.toml
samples/widgets/src/combobox.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/include/manual.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs
wx-core/src/manual.cpp

Roughly implemented ComboBox page with:
- Generate wxComboBox binding
- Add Builder for wx::ComboBox

Widgets sample: ComboBox page

---

codegen2.py
doxybindgen.toml
doxybindgen/binding.py
doxybindgen/model.py
overload_tree.md
samples/widgets/src/choice.rs
wx-core/include/generated.h
wx-core/include/manual.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs
wx-core/src/manual.cpp

Part of #77
In #78, we made this semi-automated.
Now it automatically generated by wxml metadata.

Support generating Mix-in classes automatically

---

doxybindgen.toml
doxybindgen/binding.py
doxybindgen/model.py
overload_tree.md
samples/widgets/src/combobox.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs

Closes https://github.com/kenz-gelsoft/wxRust2/issues/77 again

Rename overloads with considering ancestors

---

.github/workflows/rust.yml
codegen2.py
doxybindgen.toml
samples/widgets/src/button.rs
samples/wrapsizer/src/main.rs
wx-core/include/generated.h
wx-core/include/manual.h
wx-core/src/generated.cpp
wx-core/src/lib.rs
wx-core/src/manual.cpp

Support building with wxWidgets 3.0.x GTK+3 again

---

codegen2.py
doxybindgen.toml
samples/widgets/src/editlbox.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented EditableListBox page with:
- Generate wxEditableListBox binding
- Make wx::EditableListBox's builder

 Widgets sample: EditableListBox page

---

codegen2.py
doxybindgen.toml
samples/widgets/src/dirctrl.rs
samples/widgets/src/editlbox.rs
samples/widgets/src/filectrl.rs
samples/widgets/src/main.rs
wx-base/src/manual.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented FileCtrl page with:
- Generate wxFileCtrl binding and make its builder

Widgets sample: FileCtrl page

---

codegen2.py
doxybindgen.toml
samples/widgets/src/fontpicker.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented FontPicker page with:
- Generate wxFontPickerCtrl binding and its builder
- Generate wxFont binding

Widgets sample: FontPicker page

---

doxybindgen.toml
samples/widgets/src/gauge.rs
samples/widgets/src/main.rs
wx-base/include/generated.h
wx-base/src/generated.cpp
wx-base/src/generated.rs
wx-base/src/generated/ffi.rs
wx-base/src/generated/methods.rs
wx-base/src/lib.rs
wx-base/src/manual.cpp
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented Gauge page with:
- Generate wxGauge binding and its builder
- Generate wxTimer, wxTimerEvent binding
- Support RUST_EVT_TIMER event type

Widgets sample: Gauge page

---

codegen2.py
doxybindgen.toml
samples/widgets/src/headerctrl.rs
samples/widgets/src/hyperlink.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented Hyperlink page with:
- Generate wxHyperlinkCtrl binding and its builder

Widgets sample: Hyperlink page

---

doxybindgen.toml
doxybindgen/binding.py
doxybindgen/model.py
samples/widgets/src/editlbox.rs
samples/widgets/src/listbox.rs
samples/widgets/src/main.rs
wx-base/include/generated.h
wx-base/include/manual.h
wx-base/src/generated.cpp
wx-base/src/generated.rs
wx-base/src/generated/ffi.rs
wx-base/src/generated/methods.rs
wx-base/src/lib.rs
wx-base/src/manual.cpp
wx-core/include/generated.h
wx-core/include/manual.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs
wx-core/src/manual.cpp

Roughly implemented Listbox page with:
- Generate wxCheckListBox binding and its builder
- Generate wxClassInfo binding and implement manual up/downcast between wxCheckListBox and wxListBox
- Support non-const ref argument
- Support wxArrayInt return or argument type

Widgets sample: Listbox page

---

doxybindgen.toml
samples/widgets/src/main.rs
samples/widgets/src/slider.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented Slider page with:
- Generate wxSlider binding and its builder

Widgets sample: Slider page

---

codegen2.py
doxybindgen.toml
doxybindgen/binding.py
samples/widgets/src/main.rs
samples/widgets/src/searchctrl.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented SearchCtrl page with:
- Generate wxSearchCtrl binding and its builder
- Also closes #110

Widgets sample: SearchCtrl page

---

codegen2.py
doxybindgen.toml
samples/widgets/src/main.rs
samples/widgets/src/spinbutton.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented Spin page with:
- Generate wxSpinButton, wxSpinCtrl and wxSpinCtrlDouble binding and its builder

Widgets sample: Spin page

---

Cargo.lock
codegen2.py
doxybindgen.toml
samples/widgets/Cargo.toml
samples/widgets/src/main.rs
samples/widgets/src/timepicker.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented TimePicker page with:
- Generate wxTimePickerCtrl binding and its builder
- Add regex crate as widgets sample dependency (for text format parsing)

Widgets sample: TimePicker page

---

codegen2.py
doxybindgen.toml
samples/widgets/src/main.rs
samples/widgets/src/toggle.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented Toggle page with:
- Generate wxToggleButton, wxBitmapToggleButton binding and its builder

Widgets sample: Toggle page

---

doxybindgen.toml
samples/widgets/src/filepicker.rs
samples/widgets/src/main.rs
wx-core/include/generated.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/methods.rs
wx-core/src/lib.rs

Roughly implemented FilePicker page with:
- Generate wxFilePickerCtrl binding and its builder

Widgets sample: FilePicker page

---

doxybindgen.toml
wx-core/include/generated/ffi_a.h
wx-core/include/generated/ffi_b.h
wx-core/include/generated/ffi_g.h
wx-core/include/generated/ffi_i.h
wx-core/src/generated/class_b.rs
wx-core/src/generated/class_c.rs
wx-core/src/generated/class_i.rs
wx-core/src/generated/ffi_a.cpp
wx-core/src/generated/ffi_a.rs
wx-core/src/generated/ffi_b.cpp
wx-core/src/generated/ffi_b.rs
wx-core/src/generated/ffi_g.cpp
wx-core/src/generated/ffi_g.rs
wx-core/src/generated/ffi_i.cpp
wx-core/src/generated/ffi_i.rs
wx-core/src/generated/ffi_t.rs
wx-core/src/generated/methods_a.rs
wx-core/src/generated/methods_b.rs
wx-core/src/generated/methods_d.rs
wx-core/src/generated/methods_g.rs
wx-core/src/generated/methods_i.rs
wx-core/src/generated/methods_t.rs

Part of https://github.com/kenz-gelsoft/wxRust2/issues/119

Generate core library classes which starts with i-

---

doxybindgen.toml
wx-core/include/generated/ffi_n.h
wx-core/src/generated/class_f.rs
wx-core/src/generated/class_n.rs
wx-core/src/generated/ffi_f.rs
wx-core/src/generated/ffi_n.cpp
wx-core/src/generated/ffi_n.rs
wx-core/src/generated/methods_f.rs
wx-core/src/generated/methods_n.rs

Part of https://github.com/kenz-gelsoft/wxRust2/issues/119

Generate core library classes which starts with n-

---

doxybindgen.toml
doxybindgen/binding.py
wx-base/include/generated/ffi_c.h
wx-base/src/generated/class_c.rs
wx-base/src/generated/ffi_c.cpp
wx-base/src/generated/ffi_c.rs
wx-base/src/generated/methods_c.rs
wx-base/src/generated/methods_e.rs
wx-core/include/generated/ffi_g.h
wx-core/include/generated/ffi_t.h
wx-core/src/generated/class_d.rs
wx-core/src/generated/class_t.rs
wx-core/src/generated/ffi_g.cpp
wx-core/src/generated/ffi_g.rs
wx-core/src/generated/ffi_t.cpp
wx-core/src/generated/ffi_t.rs
wx-core/src/generated/methods_b.rs
wx-core/src/generated/methods_c.rs
wx-core/src/generated/methods_d.rs
wx-core/src/generated/methods_g.rs
wx-core/src/generated/methods_i.rs
wx-core/src/generated/methods_n.rs
wx-core/src/generated/methods_r.rs
wx-core/src/generated/methods_t.rs
wx-core/src/generated/methods_w.rs

Part of https://github.com/kenz-gelsoft/wxRust2/issues/119

Generate core library classes which starts with t-

---

doxybindgen.toml
wx-core/include/generated.h
wx-core/include/generated/ffi_w.h
wx-core/include/generated/ffi_x.h
wx-core/src/generated.cpp
wx-core/src/generated.rs
wx-core/src/generated/class_w.rs
wx-core/src/generated/class_x.rs
wx-core/src/generated/ffi.rs
wx-core/src/generated/ffi_w.cpp
wx-core/src/generated/ffi_w.rs
wx-core/src/generated/ffi_x.cpp
wx-core/src/generated/ffi_x.rs
wx-core/src/generated/methods.rs
wx-core/src/generated/methods_w.rs
wx-core/src/generated/methods_x.rs

Part of https://github.com/kenz-gelsoft/wxRust2/issues/119

Generate core library classes which starts with w-, x-, y-, z-

---

doxybindgen.toml
wx-core/include/generated/ffi_a.h
wx-core/include/generated/ffi_b.h
wx-core/include/generated/ffi_g.h
wx-core/src/generated/class_a.rs
wx-core/src/generated/class_b.rs
wx-core/src/generated/class_g.rs
wx-core/src/generated/ffi_a.cpp
wx-core/src/generated/ffi_a.rs
wx-core/src/generated/ffi_b.cpp
wx-core/src/generated/ffi_b.rs
wx-core/src/generated/ffi_g.cpp
wx-core/src/generated/ffi_g.rs
wx-core/src/generated/methods_a.rs
wx-core/src/generated/methods_b.rs
wx-core/src/generated/methods_g.rs

Generate core library classes which was pending

---

samples/hello/src/main.rs
samples/minimal/src/main.rs
samples/wrapsizer/src/main.rs

Use WeakRef for small samples

---

README.md
wx-core/README.md

- "0.0.*" doesn't match alpha versions

Fix README to build successfully

---

wx-core/include/manual.h
wx-core/src/lib.rs
wx-core/src/manual.cpp

Part of  #171
Add manual bindings for:
- Builder for wx::FileDialog
- wxLaunchDefaultBrowser()

Add Some Manual Bindings

---

wx-base/include/manual.h
wx-base/src/lib.rs
wx-base/src/manual.cpp

Support wx::EvtHandler.call_after()

---

samples/minimal/src/main.rs
wx-core/src/lib.rs

Let wx::message_box() returns its answer

---

Doxybindgen.toml
gen_binding.py
samples/widgets/src/main.rs
wx-base/src/generated/events.rs

Use better event type name for UpdateUI

---

samples/hello/src/main.rs

I've simplified the _hello_ sample a bit by using  "unwrap_or" and  "let-else" constructs.  Might as well make the hello_world as short and readable as possible.

simplified hello sample a bit
